function loadMockData() {
    if (getAllIdeas().length > 0) return;

    saveUserToDirectory({ id:'user_001', name:'Deepan K', college:'Anna University', skills:['JavaScript','React','UI Design'], profileEmoji:'⚡', joinedAt: new Date().toISOString(), ideaIds:[], bio:'Builder and idea machine' });
    saveUserToDirectory({ id:'user_002', name:'Priya S', college:'IIT Madras', skills:['Python','Machine Learning','Data Science'], profileEmoji:'🚀', joinedAt: new Date().toISOString(), ideaIds:[], bio:'ML enthusiast' });
    saveUserToDirectory({ id:'user_003', name:'Arjun R', college:'VIT Vellore', skills:['Flutter','Mobile Development','Firebase'], profileEmoji:'🎨', joinedAt: new Date().toISOString(), ideaIds:[], bio:'Mobile developer' });
    saveUserToDirectory({ id:'user_004', name:'Sneha M', college:'BITS Pilani', skills:['Node.js','Backend','MongoDB'], profileEmoji:'🔥', joinedAt: new Date().toISOString(), ideaIds:[], bio:'Backend wizard' });
    saveUserToDirectory({ id:'user_005', name:'Karthik V', college:'NIT Trichy', skills:['React','JavaScript','CSS'], profileEmoji:'💡', joinedAt: new Date().toISOString(), ideaIds:[], bio:'Frontend lover' });
    saveUserToDirectory({ id:'user_006', name:'Aishwarya B', college:'SRM Chennai', skills:['UI Design','Figma','Frontend'], profileEmoji:'🌟', joinedAt: new Date().toISOString(), ideaIds:[], bio:'UI designer' });

    saveIdea({ title:'Smart Attendance App', description:'Face recognition based attendance system for colleges. Eliminates proxy attendance completely.', tags:['EdTech','AI','MobileApp'], feasibility:82, originality:75, impact:88, verdict:'Strong concept with clear use case. Very feasible for a student team.', isPublic:true, needsTeam:true, suggestedRoles:['Frontend Developer','ML Engineer'], suggestedTeamSize:'2-3 people', ownerId:'user_001', ownerName:'Deepan K', ownerCollege:'Anna University', ownerEmoji:'⚡', heatScore:65, reactions:18, views:45, requests:6, createdAt: new Date().toISOString() });

    saveIdea({ title:'PG Food Finder', description:'Connects home cooks with PG hostel students in metro cities. Solves the daily food problem.', tags:['SocialGood','FoodTech','HyperLocal'], feasibility:78, originality:82, impact:85, verdict:'Excellent hyperlocal idea with real demand. Monetization is clear.', isPublic:true, needsTeam:true, suggestedRoles:['Frontend Developer','Backend Developer'], suggestedTeamSize:'2-3 people', ownerId:'user_002', ownerName:'Priya S', ownerCollege:'IIT Madras', ownerEmoji:'🚀', heatScore:72, reactions:20, views:55, requests:7, createdAt: new Date().toISOString() });

    saveIdea({ title:'Campus Lost and Found', description:'Mobile app for reporting and finding lost items on college campus. Uses image recognition.', tags:['MobileApp','EdTech','AI'], feasibility:88, originality:65, impact:70, verdict:'Very practical and buildable. Good first project for a student team.', isPublic:true, needsTeam:true, suggestedRoles:['Mobile Developer','Backend Developer'], suggestedTeamSize:'2 people', ownerId:'user_003', ownerName:'Arjun R', ownerCollege:'VIT Vellore', ownerEmoji:'🎨', heatScore:45, reactions:12, views:38, requests:4, createdAt: new Date().toISOString() });

    saveIdea({ title:'Study Group Matcher', description:'Algorithm that matches students with similar study goals and schedules. Like Tinder for study partners.', tags:['EdTech','SocialGood','Algorithm'], feasibility:80, originality:78, impact:82, verdict:'Smart idea targeting a real student pain point. Algorithm complexity is manageable.', isPublic:true, needsTeam:true, suggestedRoles:['Frontend Developer','Backend Developer'], suggestedTeamSize:'2-3 people', ownerId:'user_004', ownerName:'Sneha M', ownerCollege:'BITS Pilani', ownerEmoji:'🔥', heatScore:58, reactions:15, views:42, requests:5, createdAt: new Date().toISOString() });

    saveIdea({ title:'Carbon Footprint Tracker', description:'App that tracks daily carbon footprint of students and suggests eco-friendly alternatives.', tags:['Environment','MobileApp','SocialGood'], feasibility:75, originality:70, impact:90, verdict:'High impact idea with growing relevance. UI needs to be very intuitive.', isPublic:true, needsTeam:true, suggestedRoles:['Frontend Developer','UI Designer'], suggestedTeamSize:'2-3 people', ownerId:'user_005', ownerName:'Karthik V', ownerCollege:'NIT Trichy', ownerEmoji:'💡', heatScore:38, reactions:10, views:30, requests:3, createdAt: new Date().toISOString() });

    saveIdea({ title:'Mental Health Companion', description:'Anonymous peer support platform for college students dealing with stress and anxiety.', tags:['HealthTech','SocialGood','MobileApp'], feasibility:72, originality:80, impact:95, verdict:'Extremely high impact. Anonymity feature is critical and must be handled carefully.', isPublic:true, needsTeam:true, suggestedRoles:['Frontend Developer','Backend Developer','UI Designer'], suggestedTeamSize:'3 people', ownerId:'user_006', ownerName:'Aishwarya B', ownerCollege:'SRM Chennai', ownerEmoji:'🌟', heatScore:80, reactions:22, views:60, requests:8, createdAt: new Date().toISOString() });

    saveIdea({ title:'Dev Tools Dashboard', description:'All-in-one dashboard for developers to track GitHub commits, deploy status and API health.', tags:['DevTools','SocialGood','Dashboard'], feasibility:85, originality:72, impact:78, verdict:'Useful tool for developer teams. Integration with GitHub API is straightforward.', isPublic:true, needsTeam:false, suggestedRoles:['Frontend Developer'], suggestedTeamSize:'1-2 people', ownerId:'user_001', ownerName:'Deepan K', ownerCollege:'Anna University', ownerEmoji:'⚡', heatScore:52, reactions:14, views:40, requests:3, createdAt: new Date().toISOString() });

    saveIdea({ title:'Exam Prep AI', description:'AI powered exam preparation tool that generates practice questions from uploaded notes.', tags:['EdTech','AI','DevTools'], feasibility:70, originality:85, impact:88, verdict:'Very innovative use of AI for education. Gemini API integration would work perfectly here.', isPublic:true, needsTeam:true, suggestedRoles:['Frontend Developer','ML Engineer'], suggestedTeamSize:'2-3 people', ownerId:'user_003', ownerName:'Arjun R', ownerCollege:'VIT Vellore', ownerEmoji:'🎨', heatScore:68, reactions:19, views:50, requests:6, createdAt: new Date().toISOString() });
}